" /etc/vimrc

" This file is not included by default. Please prepend your .vimrc file with:
" Include the system settings
" :if filereadable( "/etc/vimrc" )
"    source /etc/vimrc
" :endif

set nocompatible           " no vi compatibility
filetype plugin indent on  " read in some essential runtime files
syntax on                  " turn on syntax highlighting
" searching
set smartcase              " makes ignorecase only apply to lowercase
set ignorecase             " lets / and ? searches ignore case
set incsearch              " searches as you type
set hlsearch               " highlight matches to the last search
" better tabbing
set shiftwidth=4           " because it's a common choice (tabsize)
set expandtab              " insert spaces instead of real tabs
set smarttab               " smarter use of tab key (trust me)
" quality of life things
set autoindent             " when starting new line, copy indentation
set history=50             " extend command history
set ruler                  " shows line and character at bottom right
set bs=indent,eol,start    " always allow backspacing
set nojoinspaces           " never double space after periods
set lazyredraw             " don't redraw when it's not needed
" command tab completion
set wim=longest,list,full  " wildmode: says how tab completion works
set wildmenu               " extends wildmode to be interactable

" Syntax Highlighting for strange filenames
au BufRead,BufNewFile screenrc  set syntax=screen
au BufRead,BufNewFile gitconfig set syntax=gitconfig
au BufRead,BufNewFile *.g4      set syntax=antlr4

